apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds
- workflow-controller
- argo-server
images:
- name: argoproj/argocli
  newName: argoproj/argocli
  newTag: v2.5.0-rc1
- name: argoproj/workflow-controller
  newName: argoproj/workflow-controller
  newTag: v2.5.0-rc1
